### ISSUE TITLE
TypeError: import_coc2.RelativePattern is not a constructor

### ISSUE THREAD

**Issue by stfnwp** [yaegassy/coc-tailwindcss3#3]
After installing this extension, I get the following error after nvim startup:
(output of :CocInfo)
```
22-04-25T17:08:47.389 ERROR (pid:2806) [server] - unhandledRejection  Promise {                                                                                                                                                    
     <rejected> TypeError: import_coc2.RelativePattern is not a constructor
         at didOpenTextDocument (/home/stefan/.local/share/nvim/plugged/coc-tailwindcss3/lib/index.js:1036:64)
         at Array.forEach (<anonymous>)                                                                                                                                                                         
         at Object.activate (/home/stefan/.local/share/nvim/plugged/coc-tailwindcss3/lib/index.js:1042:39)
         at /home/stefan/.local/share/nvim/plugged/coc.nvim/build/index.js:231:1411                                                                                                                             
         at new Promise (<anonymous>)                                                                                                                                                                           
         at Object.activate (/home/stefan/.local/share/nvim/plugged/coc.nvim/build/index.js:231:1369)
         at i5.activate (/home/stefan/.local/share/nvim/plugged/coc.nvim/build/index.js:228:7366)
         at /home/stefan/.local/share/nvim/plugged/coc.nvim/build/index.js:230:283
         at new Promise (<anonymous>)
        at s (/home/stefan/.local/share/nvim/plugged/coc.nvim/build/index.js:230:45)
 } 
```
And the plugin is not usable for me :-(

**Comment by yaegassy** [comment]
I have never encountered that error. can you tell me what version of node.js you are using? Also, please update your coc.nvim to the latest version if possible.

**Comment by stfnwp** [comment]
Using the latest version of coc.nvim did the trick :+1: 
Sorry for the inconveniences, but I somehow mixed up :CocUpdate with :PlugUpdate :see_no_evil:
